[tool.black]
line-length = 120

[tool.isort]
line_length = 120
profile = "black"

[tool.flake8]
max-line-length = 120
docstring_style = "sphinx"

[tool.pylint]
max-line-length = 120
disable = "missing-module-docstring, too-few-public-methods, too-many-ancestors"

[tool.pyproject-fmt]
column_width = 120

[tool.mypy]
plugins = ["pydantic.mypy", "mypy_django_plugin.main" ]
strict = 1

[[tool.mypy.overrides]]
module = ["rest_framework.*"]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "ArcTracker.settings"
